Repository Normation/ncf, pull requests merged in 2018-06, with the labels that each got.

#767 Fixes #12720: Technique Editor may ignores some error when authenticating
  api/ncf_api_flask_app/views.py
  qa-test
Labels: qa: Can't merge

#768 Fixes #12759: Reporting bundle generated ae invalid : Conflicting arity in calling bundle log_rudder, expected 5 arguments, 4 given
  tests/acceptance/30_generic_methods/log_rudder.cf
  tests/unit/test_ncf_rudder.py
  tests/unit/test_technique_rudder_reporting.cf
  tools/ncf.py
  tools/ncf_rudder.py
Labels: Ready for merge

#770 Fixes #12761: Add the possibility to customize filters and tests for jinja2 templating
  tree/10_ncf_internals/modules/templates/jinja2-templating.py
  tree/30_generic_methods/file_from_template_jinja2.cf
Labels: Ready for merge, qa: Can't merge

#772 Fixes #12769: Improve documentation on adding tests & filters for Jinja2
  tree/30_generic_methods/file_from_template_jinja2.cf
Labels: Ready for merge, qa: Can't merge

#773 Fixes #12767: Add a test for custom jinja filters and tests
  tests/acceptance/30_generic_methods/file_from_template_jinja2.custom_filter.cf
  tests/acceptance/30_generic_methods/file_from_template_jinja2.custom_filter.cf.expected
  tests/acceptance/30_generic_methods/file_from_template_jinja2.custom_filter.cf.j2
  tests/acceptance/30_generic_methods/file_from_template_jinja2.custom_filter.cf.py
  tree/10_ncf_internals/initialization.cf
  tree/10_ncf_internals/modules/templates/jinja2-templating.py
  tree/30_generic_methods/file_from_template_jinja2.cf
Labels: Ready for merge, qa: Can't merge

#764 Fixes #12593: Add support for BSD-style init scripts services (rc.d) (slackware)
  tree/20_cfe_basics/ncf_lib.cf
  tree/30_generic_methods/_classes_combine_two.cf
  tree/30_generic_methods/_classes_copy.cf
  tree/30_generic_methods/service_check_started_at_boot.cf
Labels: qa: Can't merge

#777 Fixes #12798: zypper module arch and version specification for zypper commands is not correct
  tree/10_ncf_internals/modules/packages/zypper
Labels: qa: Can't merge

#778 Fixes #12127: Backport options for yum package provider
  tree/10_ncf_internals/modules/packages/yum
Labels: qa: Can't merge

#779 Fixes #12799: Force using epoch when installing a package with zypper
  tree/10_ncf_internals/modules/packages/zypper
  tree/30_generic_methods/package_state.cf
Labels: qa: Can't merge

#761 Fixes #12597: Do not modify variables in existing bundles
  tree/10_ncf_internals/initialization.cf
  tree/20_cfe_basics/log_rudder.cf
Labels: Ready for merge

#783 Fixes #12811: Synchronize the 'slackpkg' cfengine package module shipped with ncf with the official one
  tree/10_ncf_internals/modules/packages/slackpkg
Labels: qa: Can't merge

#785 Fixes #12823: Same as parent for dry-run
  tree/10_ncf_internals/initialization.cf
  tree/20_cfe_basics/dry_run_lib.cf
Labels: qa: Can't merge

#782 Fixes #10907: Synchronize package modules from masterfiles
  tree/10_ncf_internals/modules/packages/apt_get
Labels: qa: Can't merge

#708 Fixes #12154: Create a generic method to define environment variable
  tree/30_generic_methods/environment_variable.cf
Labels: Ready for merge, qa: Can't merge
