Repository Normation/ncf, pull requests merged in 2018-02, with the labels that each got.

#692 Fixes #11836: sharedfile_to_node reports repaired even if it fails
  tree/30_generic_methods/sharedfile_to_node.cf
Labels: Ready for merge, qa: Can't merge

#703 Fixes #12114: parent patch broke tests
  tools/ncf_rudder.py
Labels: Ready for merge, qa: Can't merge

#700 Fixes #12102: Parent patch broke tests (again)
  builder/js/ncf.js
  qa-test
  tools/ncf_rudder.py
Labels: Ready for merge, qa: Can't merge

#702 Fixes #12044: Add a script to rewrite a technique from command line
  ncf
  tools/ncf.py
Labels: qa: Can't merge

#705 Fixes #11610: file_copy_with_check
  tests/acceptance/30_generic_methods/file_copy_from_local_source_with_check.cf
  tree/30_generic_methods/file_copy_from_local_source_with_check.cf
Labels: Ready for merge
