Repository Normation/ncf, pull requests merged in 2018-07, with the labels that each got.

#787 Fixes #12887: fail to restart certain services on Ubuntu because of incomplete detection of systemd/upstart
  tree/20_cfe_basics/ncf_lib.cf
Labels: qa: Can't merge

#788 Fixes #12237: Add examples in documentation of condition_from_expression
  tree/30_generic_methods/condition_from_command.cf
  tree/30_generic_methods/condition_from_expression.cf
  tree/30_generic_methods/condition_from_expression_persistent.cf
Labels: qa: Can't merge

#789 Fixes #12921: Wrong bundle name passed in 12154
  tree/30_generic_methods/environment_variable.cf
Labels: qa: Can't merge

#790 Fixes #12468: dsc filter in technique editor does not seem to work
  builder/js/ncf.js
Labels: Ready for merge

#791 Fixes #12953: In some cases, reporting context calls can be the same for different methods, and hence ignored
  tools/ncf.py
  tools/ncf_rudder.py
Labels: Ready for merge

#792 Fixes #12957: On debian 9.4, ncf views.py can not access http://localhost/rudder (but can https://..)
  api/ncf_api_flask_app/views.py
Labels: Ready for merge

#793 Fixes #12970: Broken technique editor if a technique is in the browser cache, but has been removed from the FS
  builder/js/ncf.js
Labels: Ready for merge, qa: Can't merge

#775 Fixes #12779: Some more buttons to make consistent in the Technique Editor
  builder/css/custom.css
  builder/index.html
Labels: qa: Can't merge

#795 Fixes #12997: ncf_package unsupported "absence" of "latest" version of a package is not clear enough
  tree/20_cfe_basics/package_lib.cf
Labels: qa: Can't merge
