Repository Normation/ncf, pull requests merged in 2018-03, with the labels that each got.

#716 Fixes #12181: typo in new logger
  tree/30_generic_methods/service_stop.cf
Labels: Ready for merge

#707 Fixes #12147: We cannot use file_enforce_content with a list and enforce=true
  tests/acceptance/30_generic_methods/file_enforce_content.cf
  tree/30_generic_methods/file_enforce_content.cf
Labels: qa: Can't merge

#714 Fixes #12176: Remove doc of class_prefix variable
  tree/30_generic_methods/condition_from_command.cf
  tree/30_generic_methods/condition_from_expression.cf
  tree/30_generic_methods/condition_from_expression_persistent.cf
Labels: Ready for merge

#722 Fixes #12335: typo in name of method used in write_all_techniques
  ncf
Labels: Ready for merge, qa: Can't merge
