Repository Normation/ncf, pull requests merged in 2019-12, with the labels that each got.

#1112 Fixes #16226: Error when importing technique with missing component in a method call
  tools/ncf.py
Labels: qa: Can't merge

#1120 Fixes #16336: Custom methods don't appear in technique editor anymore
  tools/ncf.py
Labels: Ready for merge

#1119 Fixes #16323: Wrong condition on component used when importing technique
  tools/ncf.py
Labels: Ready for merge, qa: Can't merge

#1121 Fixes #16314: Type for parameters of methods in technique editor
  builder/index.html
  builder/js/ncf.js
  tests/unit/test_ncf.py
  tools/ncf.py
Labels: qa: Can't merge

#1123 Fixes #16359: condition_from_commands is not running any command in audit mode
  tree/30_generic_methods/condition_from_command.cf
Labels: qa: Can't merge
