Repository Normation/ncf, pull requests merged in 2019-11, with the labels that each got.

#1095 Fixes #16092: Fix internal links
  tree/30_generic_methods/condition_once.cf
  tree/30_generic_methods/directory_create.cf
  tree/30_generic_methods/file_copy_from_local_source.cf
  tree/30_generic_methods/file_copy_from_local_source_recursion.cf
  tree/30_generic_methods/file_copy_from_local_source_with_check.cf
  tree/30_generic_methods/file_copy_from_remote_source.cf
  tree/30_generic_methods/file_copy_from_remote_source_recursion.cf
  tree/30_generic_methods/file_create.cf
  tree/30_generic_methods/file_create_symlink.cf
  tree/30_generic_methods/file_create_symlink_enforce.cf
  tree/30_generic_methods/file_create_symlink_force.cf
  tree/30_generic_methods/file_download.cf
  tree/30_generic_methods/file_enforce_content.cf
  tree/30_generic_methods/file_ensure_block_in_section.cf
  tree/30_generic_methods/file_ensure_block_present.cf
  tree/30_generic_methods/file_ensure_key_value.cf
  tree/30_generic_methods/file_ensure_key_value_option.cf
  tree/30_generic_methods/file_ensure_key_value_parameter_in_list.cf
  tree/30_generic_methods/file_ensure_key_value_parameter_not_in_list.cf
  tree/30_generic_methods/file_ensure_key_value_present_in_ini_section.cf
  tree/30_generic_methods/file_ensure_keys_values.cf
  tree/30_generic_methods/file_ensure_line_present_in_ini_section.cf
  tree/30_generic_methods/file_ensure_line_present_in_xml_tag.cf
  tree/30_generic_methods/file_ensure_lines_absent.cf
  tree/30_generic_methods/file_ensure_lines_present.cf
  tree/30_generic_methods/file_from_remote_source.cf
  tree/30_generic_methods/file_from_template.cf
  tree/30_generic_methods/file_from_template_jinja2.cf
  tree/30_generic_methods/file_from_template_mustache.cf
  tree/30_generic_methods/file_from_template_type.cf
  tree/30_generic_methods/file_keys_values_present.cf
  tree/30_generic_methods/file_remove.cf
  tree/30_generic_methods/file_template_expand.cf
  tree/30_generic_methods/package_absent.cf
  tree/30_generic_methods/package_install.cf
  tree/30_generic_methods/package_install_version.cf
  tree/30_generic_methods/package_install_version_cmp.cf
  tree/30_generic_methods/package_install_version_cmp_update.cf
  tree/30_generic_methods/package_present.cf
  tree/30_generic_methods/package_remove.cf
  tree/30_generic_methods/package_state.cf
  tree/30_generic_methods/package_state_options.cf
  tree/30_generic_methods/permissions_dirs_recurse.cf
  tree/30_generic_methods/permissions_recurse.cf
  tree/30_generic_methods/service_ensure_disabled_at_boot.cf
  tree/30_generic_methods/service_ensure_running.cf
  tree/30_generic_methods/service_ensure_running_path.cf
  tree/30_generic_methods/service_ensure_started_at_boot.cf
  tree/30_generic_methods/service_ensure_stopped.cf
  tree/30_generic_methods/service_reload.cf
  tree/30_generic_methods/service_restart.cf
  tree/30_generic_methods/service_restart_if.cf
  tree/30_generic_methods/service_start.cf
  tree/30_generic_methods/service_stop.cf
  tree/30_generic_methods/sharedfile_from_node.cf
  tree/30_generic_methods/sharedfile_to_node.cf
  tree/30_generic_methods/user_create.cf
  tree/30_generic_methods/variable_dict_from_file.cf
  tree/30_generic_methods/variable_dict_merge.cf
  tree/30_generic_methods/variable_dict_merge_tolerant.cf
Labels: Ready for merge, qa: Can't merge

#1096 Fixes #16098: Fix link to external doc in technique editor
  builder/js/ncf.js
Labels: Ready for merge, qa: Can't merge

#1097 Fixes #16097: Update ncf README
  README.md
Labels: Ready for merge

#1101 Fixes #11587: Ensure service (re)started does now work if systemd hit "start-limit"
  tree/20_cfe_basics/services.cf
Labels: qa: Can't merge

#1103 Fixes #12780: Do not store response when response code is an error in file_fom_http_server
  tree/30_generic_methods/file_from_http_server.cf
Labels: qa: Can't merge

#1104 Fixes #15509: Prevent setting an empty report component
  builder/index.html
  tools/ncf.py
Labels: qa: Can't merge

#1100 Fixes #15178: In technique editor, deleting a new technique crashes
  builder/index.html
  builder/js/ncf.js
Labels: qa: Can't merge

#1108 Fixes #16181: Missing edit_lines promises in dry-run lib
  tests/acceptance/20_cfe_basics/dry_run_lib_specific_class.cf
  tree/20_cfe_basics/dry_run.cf
Labels: qa: Can't merge

#1093 Fixes #15447: Improve zypper pattern error log
  tree/10_ncf_internals/modules/packages/zypper
  tree/10_ncf_internals/modules/packages/zypper_pattern
Labels: Ready for merge

#1114 Fixes #16271: Service reload tests are failing in 6.0 on debian like systems
  tests/acceptance/30_generic_methods/unsafe/service_reload.cf
Labels: qa: Can't merge

#1113 Fixes #16267: Copying a file to a directory using the "file_from_shared_folder" GM result in a success report even if nothing is done
  tree/20_cfe_basics/ncf_lib.cf
Labels: qa: Can't merge

#1110 Fixes #16220: ACLS GM are not working in recurse mode
  tests/acceptance/30_generic_methods/permissions_acl_entry.recursive.audit.error.cf
  tests/acceptance/30_generic_methods/permissions_acl_entry.recursive.audit.success.cf
  tests/acceptance/30_generic_methods/permissions_acl_entry.recursive.repaired.cf
  tests/acceptance/30_generic_methods/permissions_acl_entry.recursive.success.cf
  tests/acceptance/30_generic_methods/permissions_group_acl_present.cf
  tests/acceptance/30_generic_methods/permissions_other_acl_present.cf
  tests/acceptance/30_generic_methods/permissions_user_acl_present.cf
  tree/30_generic_methods/permissions_acl_entry.cf
  tree/30_generic_methods/permissions_group_acl_present.cf
  tree/30_generic_methods/permissions_other_acl_present.cf
  tree/30_generic_methods/permissions_user_acl_present.cf
Labels: qa: Can't merge

#1117 Fixes #16275: Add a generic method to escape regex chars in a string
  tests/acceptance/30_generic_methods/variable_string_escaped.cf
  tree/30_generic_methods/variable_string_escaped.cf
Labels: Ready for merge, qa: Can't merge
