Repository Normation/ncf, pull requests merged in 2020-05, with the labels that each got.

#1182 UserStory #17196: Use Augeas Binaries To get, set and execute commands.
  tests/acceptance/30_generic_methods/file_augeas_commands.cf
  tests/acceptance/30_generic_methods/unsafe/file_augeas_set.cf
  tests/acceptance/30_generic_methods/variable_string_from_augeas.cf
  tree/20_cfe_basics/paths.cf
  tree/30_generic_methods/file_augeas_commands.cf
  tree/30_generic_methods/file_augeas_set.cf
  tree/30_generic_methods/variable_string_from_augeas.cf
Labels: Ready for merge

#1195 Fixes #17400: Technique diverge popup when comming back to a techniques because of a change of category
  builder/js/ncf.js
Labels: Ready for merge, qa: Can't merge

#1196 Fixes #17425: techniques files are parsed twice
  tools/ncf.py
Labels: Ready for merge, qa: Can't merge

#1201 Fixes #17475: Remove non-ASCII parameters from Augeas generic methods documentation
  tree/30_generic_methods/file_augeas_commands.cf
  tree/30_generic_methods/file_augeas_set.cf
  tree/30_generic_methods/variable_string_from_augeas.cf
Labels: Ready for merge

#1204 Fixes #17415: Missing information that markdown is supported for technique documentation
  builder/css/custom.css
  builder/css/markdown-mark-solid.svg
  builder/index.html
Labels: qa: Can't merge
