Repository Normation/ncf, pull requests merged in 2020-04, with the labels that each got.

#1172 Fixes #16235: Text & Boxes jump when displaying missing inputs
  builder/css/custom.css
  builder/index.html
  builder/js/ncf.js
Labels: qa: Can't merge

#1176 Fixes #17135: Remove ncf rest api
  Makefile
  api/README.md
  api/ncf_api_flask_app/__init__.py
  api/ncf_api_flask_app/views.py
  api/requirements.txt
  api/run.py
  api/setup_dev_env.sh
  tools/ncf-builder.conf
Labels: Ready for merge

#1175 Fixes #17134: Adapt technique editor to not call ncf api and add method to generate data for Rudder
  builder/index.html
  builder/js/ncf.js
  ncf
Labels: Ready for merge

#1160 Fixes #16925: Show the list of fields that have been modified when a technique diverges
  builder/css/custom.css
  builder/index.html
  builder/js/ncf.js
Labels: Ready for merge

#1166 Fixes #16937: Keep the original name of a Generic Method displayed
  builder/css/custom.css
  builder/index.html
  builder/js/ncf.js
Labels: Ready for merge, qa: Can't merge

#1174 Fixes #17078: Improve UX for technique resource files
  builder/css/custom.css
  builder/index.html
  builder/js/ncf.js
Labels: Ready for merge, qa: Can't merge

#1180 Fixes #17206: missing ng-init after rebase
  builder/index.html
Labels: Ready for merge

#1188 Fixes #17256: Parent broke policies
  tree/20_cfe_basics/def.cf
  tree/20_cfe_basics/packages.cf
Labels: Ready for merge
