Repository Normation/ncf, pull requests merged in 2021-09, with the labels that each got.

#1308 Fixes #19970: Add ncf tests to the repo Jenkinsfile
  Jenkinsfile
Labels: Trigger test

#1307 Fixes #19908: Strict mode of file_key_value_present_option does not introduce unwanted escpaing characters
  Jenkinsfile
  tests/acceptance/30_generic_methods/file_key_value_option.cf
  tree/20_cfe_basics/files.cf
  tree/30_generic_methods/file_key_value_present_option.cf
Labels: Ready for merge, qa: Can't merge, Trigger test

#1309 Fixes #19979: Cover all supported server OS in the PR automated tests.
  Jenkinsfile
Labels: Trigger test

#1311 Fixes #19992: error in file_key_value_present_in_ini_section
  tree/30_generic_methods/file_key_value_present_in_ini_section.cf
Labels: Ready for merge, Trigger test

#1312 Fixes #20001: testinfra based tests should pass via the python executable and not py.test
  tests/acceptance/default_ncf.cf.sub
Labels: Trigger test

#1310 Fixes #18868: Improve parameter naming
  .gitignore
  tree/30_generic_methods/condition_from_expression.cf
  tree/30_generic_methods/condition_from_expression_persistent.cf
  tree/30_generic_methods/file_content.cf
  tree/30_generic_methods/group_absent.cf
  tree/30_generic_methods/group_present.cf
  tree/30_generic_methods/service_restart_if.cf
  tree/30_generic_methods/variable_dict.cf
  tree/30_generic_methods/variable_dict_from_file.cf
  tree/30_generic_methods/variable_dict_from_file_type.cf
  tree/30_generic_methods/variable_dict_from_osquery.cf
  tree/30_generic_methods/variable_dict_merge.cf
  tree/30_generic_methods/variable_dict_merge_tolerant.cf
  tree/30_generic_methods/variable_iterator.cf
  tree/30_generic_methods/variable_iterator_from_file.cf
  tree/30_generic_methods/variable_string.cf
  tree/30_generic_methods/variable_string_default.cf
  tree/30_generic_methods/variable_string_escaped.cf
  tree/30_generic_methods/variable_string_from_augeas.cf
  tree/30_generic_methods/variable_string_from_command.cf
  tree/30_generic_methods/variable_string_from_file.cf
  tree/30_generic_methods/variable_string_from_math_expression.cf
  tree/30_generic_methods/variable_string_match.cf
Labels: Trigger test
