Repository Normation/ncf, pull requests merged in 2022-05, with the labels that each got.

#1344 Fixes #20913: multiple calls to file_from_template_jinja2 in audit fails
  tree/30_generic_methods/file_from_template_jinja2.cf
Labels: Ready for merge, qa: Can't merge, Trigger test

#1354 Fixes #21130: Improve cleanup of root-owned files in tests
  Jenkinsfile
Labels: Ready for merge, Trigger test

#1355 Fixes #21178: Ci does not properly clean its test files
  Jenkinsfile
Labels: Ready for merge

#1353 Fixes #21088: Reporting issues when using multiple directives of the same technique on a node
  tests/acceptance/default_ncf.cf.sub
  tree/20_cfe_basics/log_rudder.cf
  tree/30_generic_methods/package_absent.cf
  tree/30_generic_methods/package_present.cf
  tree/30_generic_methods/package_state.cf
  tree/30_generic_methods/package_state_options.cf
  tree/30_generic_methods/service_disabled.cf
  tree/30_generic_methods/service_started.cf
  tree/30_generic_methods/service_stopped.cf
Labels: Ready for merge, Trigger test
