Repository Normation/ncf, pull requests merged in 2022-09, with the labels that each got.

#1366 Fixes #21737: Improve the windows documentation for condition_from_command
  tree/30_generic_methods/condition_from_command.cf
Labels: Ready for merge, qa: Can't merge

#1365 Fixes #21734: Improve the command_execution documentation for windows
  tree/30_generic_methods/command_execution.cf
Labels: Ready for merge

#1369 Fixes #21763: Add an audit command generic method
  tests/acceptance/30_generic_methods/command_execution.cf
  tests/acceptance/30_generic_methods/command_execution_result.cf
  tests/acceptance/default_ncf.cf.sub
  tests/acceptance/testall
  tree/30_generic_methods/audit_from_command.cf
  tree/30_generic_methods/command_execution.cf
  tree/30_generic_methods/command_execution_result.cf
Labels: qa: Can't merge
