Repository Normation/ncf, pull requests merged in 2022-03, with the labels that each got.

#1335 Fixes #20806: Use the new logger v4 for service methods
  tree/20_cfe_basics/log_rudder.cf
  tree/20_cfe_basics/services.cf
  tree/30_generic_methods/package_absent.cf
  tree/30_generic_methods/service_action.cf
  tree/30_generic_methods/service_check_running.cf
  tree/30_generic_methods/service_stop.cf
  tree/30_generic_methods/service_stopped.cf
Labels: Trigger test, WIP

#1329 Fixes #20612: No report from sysctl generic method
  tree/30_generic_methods/sysctl_value.cf
Labels: Trigger test

#1337 Fixes #20850: Some service methods don't report correctly
  tree/20_cfe_basics/common.cf
  tree/30_generic_methods/service_action.cf
  tree/30_generic_methods/service_check_disabled_at_boot.cf
  tree/30_generic_methods/service_check_running.cf
  tree/30_generic_methods/service_check_running_ps.cf
  tree/30_generic_methods/service_check_started_at_boot.cf
  tree/30_generic_methods/service_disabled.cf
  tree/30_generic_methods/service_enabled.cf
  tree/30_generic_methods/service_ensure_disabled_at_boot.cf
  tree/30_generic_methods/service_ensure_running.cf
  tree/30_generic_methods/service_ensure_running_path.cf
  tree/30_generic_methods/service_ensure_started_at_boot.cf
  tree/30_generic_methods/service_ensure_stopped.cf
  tree/30_generic_methods/service_reload.cf
  tree/30_generic_methods/service_restart.cf
  tree/30_generic_methods/service_restart_if.cf
  tree/30_generic_methods/service_start.cf
  tree/30_generic_methods/service_started.cf
  tree/30_generic_methods/service_started_path.cf
  tree/30_generic_methods/service_stop.cf
  tree/30_generic_methods/service_stopped.cf
Labels: Trigger test

#1338 Fixes #20864: use report_id for command_execution generic method
  tests/acceptance/30_generic_methods/command_execution.cf
  tests/acceptance/30_generic_methods/command_execution_once.cf
  tests/acceptance/30_generic_methods/command_execution_result.cf
  tests/acceptance/default_ncf.cf.sub
  tree/30_generic_methods/command_execution.cf
  tree/30_generic_methods/command_execution_once.cf
  tree/30_generic_methods/command_execution_result.cf
Labels: Trigger test

#1330 Fixes #5684: Generic method to raise a reinventory
  tree/30_generic_methods/rudder_inventory_trigger.cf
Labels: Ready for merge, Trigger test

#1340 Fixes #20882: Adapt new rudder report to work with techniques
  tree/20_cfe_basics/log_rudder.cf
  tree/20_cfe_basics/services.cf
  tree/30_generic_methods/service_ensure_running.cf
  tree/30_generic_methods/service_ensure_stopped.cf
  tree/30_generic_methods/service_started.cf
  tree/30_generic_methods/service_stopped.cf
Labels: Trigger test

#1339 Fixes #20863: Broken reporting for double nested method calls
  tree/20_cfe_basics/common.cf
  tree/30_generic_methods/command_execution.cf
  tree/30_generic_methods/command_execution_once.cf
  tree/30_generic_methods/command_execution_result.cf
  tree/30_generic_methods/service_ensure_disabled_at_boot.cf
  tree/30_generic_methods/service_ensure_running.cf
  tree/30_generic_methods/service_ensure_running_path.cf
  tree/30_generic_methods/service_ensure_started_at_boot.cf
  tree/30_generic_methods/service_ensure_stopped.cf
  tree/30_generic_methods/service_reload.cf
  tree/30_generic_methods/service_restart.cf
  tree/30_generic_methods/service_restart_if.cf
  tree/30_generic_methods/service_start.cf
  tree/30_generic_methods/service_stop.cf
Labels: Trigger test

#1343 Fixes #20128: Variable string from command fails when command contains control structures
  tree/30_generic_methods/variable_string_from_command.cf
Labels: Ready for merge, Trigger test

#1346 Fixes #20921: Adapt parent ticket for 7.0
  tree/30_generic_methods/variable_string_from_command.cf
Labels: Ready for merge, Trigger test

#1349 Fixes #18553: Allow managing other types of systemd units
  tree/20_cfe_basics/services.cf
Labels: Trigger test

#1348 Fixes #20944: Broken reporting for double nested method calls
  tree/20_cfe_basics/log_rudder.cf
  tree/30_generic_methods/service_started.cf
  tree/30_generic_methods/service_stopped.cf
Labels: Trigger test
