Repository Normation/ncf, pull requests merged in 2023-08, with the labels that each got.

#1403 Fixes #23277: Improve some messages - ncf
  Jenkinsfile
  tree/10_ncf_internals/initialization.cf
  tree/10_ncf_internals/list-compatible-inputs
  tree/20_cfe_basics/common.cf
  tree/20_cfe_basics/dry_run.cf
  tree/20_cfe_basics/log_rudder.cf
  tree/30_generic_methods/_classes_combine_ifthenelse.cf
  tree/30_generic_methods/command_execution.cf
  tree/30_generic_methods/file_from_template_jinja2.cf
  tree/30_generic_methods/file_key_value_parameter_present_in_list.cf
  tree/30_generic_methods/permissions_dirs_recurse.cf
  tree/30_generic_methods/schedule_simple_catchup.cf
  tree/30_generic_methods/service_action.cf
  tree/30_generic_methods/variable_string_from_augeas.cf
Labels: qa: Can't merge

#1294 Fixes #10713: Document when a parameter can be a regex
  tree/30_generic_methods/file_lines_absent.cf
  tree/30_generic_methods/file_lines_present.cf
Labels: qa: Can't merge, Trigger test

#1385 Fixes #22584: "Variable string from command" creates empty files in /var/rudder/modified-files
  tree/30_generic_methods/variable_string_from_command.cf
Labels: Ready for merge, qa: Can't merge

#1406 Fixes #23347: Improve variable_string_from_command by using execresult_as_data
  tests/acceptance/30_generic_methods/variable_string_from_command.cf
  tree/30_generic_methods/variable_string_from_command.cf
Labels: Ready for merge, qa: Can't merge
